[ui]
theme = "catppuccin-mocha"

[revisions]
revset = "present(@) | ancestors(immutable().., 10) | present(trunk())"               # overrides jj's revsets.log

[preview]
file_command = ["diff", "--color", "always", "-r", "$change_id", "$file", "--config", "ui.diff-formatter=delta-catppuccin-mocha"]
oplog_command = ["op", "show", "$operation_id", "--color", "always"]
revision_command = ["show", "--color", "always", "-r", "$change_id", "--config", "ui.diff-formatter=delta-catppuccin-mocha"]
position = "auto" # auto, bottom, or right
width_percentage = 66.6
show_at_start = false
