[buildPlans.HunterMono]
family = "Hunter Mono"
spacing = "term"
serifs = "sans"
noCvSs = false
exportGlyphNames = false

  [buildPlans.HunterMono.variants]
  inherits = "ss08"

    [buildPlans.HunterMono.variants.design]
    six = "straight-bar"
    seven = "curly-serifless"
    eight = "crossing-asymmetric"
    nine = "straight-bar"
    zero = "oval-slashed"
    capital-a = "curly-serifless"
    capital-m = "hanging-serifless"
    capital-n = "asymmetric-serifless"
    capital-q = "straight"
    capital-r = "curly-serifless"
    capital-y = "curly-serifless"
    a = "double-storey-serifless"
    b = "bottom-cut-serifless"
    f = "serifless"
    g = "single-storey-top-cut"
    i = "serifed-flat-tailed"
    j = "serifed"
    k = "straight-serifless"
    l = "serifed-flat-tailed"
    q = "top-cut-tailed-serifless"
    t = "flat-hook"
    y = "curly-serifless"
    cyrl-a = "double-storey-serifless"
    caret = "medium"
    number-sign = "upright"
    at = "threefold"
    dollar = "open"
    percent = "rings-continuous-slash"
    question = "smooth"
    lig-neq = "slightly-slanted"
    lig-equal-chain = "with-notch"
    lig-hyphen-chain = "with-notch"
    lig-plus-chain = "with-notch"
    lig-double-arrow-bar = "without-notch"
    lig-single-arrow-bar = "without-notch"

    [buildPlans.HunterMono.variants.italic]
    six = "straight-bar"
    seven = "curly-serifless"
    eight = "crossing-asymmetric"
    nine = "straight-bar"
    zero = "oval-slashed"
    capital-a = "curly-serifless"
    capital-m = "hanging-serifless"
    capital-n = "asymmetric-serifless"
    capital-q = "curly-tailed"
    capital-r = "curly-serifless"
    capital-y = "curly-serifless"
    a = "single-storey-tailed"
    b = "bottom-cut-serifless"
    f = "serifless"
    g = "single-storey-top-cut"
    i = "serifed-flat-tailed"
    j = "serifed"
    k = "cursive-serifless"
    l = "serifed-flat-tailed"
    q = "top-cut-diagonal-tailed-serifless"
    t = "flat-hook"
    y = "curly-turn-serifless"
    cyrl-a = "single-storey-serifed"
    caret = "medium"
    number-sign = "upright"
    at = "threefold"
    dollar = "open"
    percent = "rings-continuous-slash"
    question = "smooth"
    lig-neq = "slightly-slanted"
    lig-equal-chain = "with-notch"
    lig-hyphen-chain = "with-notch"
    lig-plus-chain = "with-notch"
    lig-double-arrow-bar = "without-notch"
    lig-single-arrow-bar = "without-notch"

  [buildPlans.HunterMono.ligations]
  inherits = "dlig"

[buildPlans.HunterMono.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.HunterMono.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.HunterMono.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.HunterMono.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.HunterMono.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
